### ISSUE TITLE
Add songs to a given playlist

### ISSUE THREAD

**Issue by MFreeze** [boysetsfrog/vimpc#58]
Currently the only way to add songs to a playlist which isn't loaded is the command `toplaylist`. But this command creates a new playlist. Would it be possible to add a command allowing the user to append some songs to an existing playlist?

I'm not sure to be clear enough, since my english can be a little messy...

Actually, I use playlists as a rating system from 1 to 5 stars, and I would like to be able, when I'm listening to a music, to add this one to one of the previous playlist without having to load the latter, and save it. I didn't find yet a way to do it.

**Comment by GSI** [comment]
Exactly what I would love to have too. Currently there is the write command `:w`.

Vim-style, an according append command would look like this `:w! >> some_playlist`.

Meanwhile, here is a workaround you may use in your scripts:

<pre>echo "`mpc --format %file% | head -n1`" >> path/to/your/playlist.m3u</pre>

**Comment by connermcd** [comment]
@GSI @MFreeze this feature was actually implemented in f0b6a0b - when you load a playlist, add or remove songs, and then `:save` it will save the new playlist. Cheers!

**Comment by GSI** [comment]
The functionality we are looking for is actually "sending" a given track to a playlist **without having to open that list first** - just as the CLI-command I use does.

**Comment by connermcd** [comment]
Fixed with c42b095 which allows the "info window" to use the `:toplaylist` command. Basically, find the song you want to add in a given playlist, library, browse or other tab and press `e` to open the info window. Then use `:toplaylist <name>` where `<name>` is the name of the playlist you want to add it to.

This command already works with tabs that contain a selection of songs such as after `:findartist` etc. Hope this helps.
